---
title: "R Notebook"
output: html_notebook
---
# Run Add_support_read_info_combined.R first. 

# Below are the stats we extracted

|Caller| SV support        | Total depth             | Note                 |
|:-----|:------------------|:-----------------------:|:---------------------|
|Delly | DR                | DR + DV                 |                      |
|SvABA | AD                | DP                      | DP=total depth       |
|Manta | PR[2] + SR[2]     | SR[1]+SR[2]+PR[1]+PR[2] | SR lists both the alt & ref so you need to split it  |
|Wham  | A                 | n/a                     |                      |
|Melt  | LP, RP            | LP + RP                 |                      |

# Packages
```{r}
library(StructuralVariantAnnotation)
```

# Truth set
```{r}
setwd("~/GitRepo/summerproject2021/NA12878_benchmark/Maestro_scripts/VCF")

personalis_vcf=readVcf("test_personalis_hg38.vcf")
spiral_vcf=readVcf("test_spiral_hg38.vcf")

truth_vcf=rbind(personalis_vcf, spiral_vcf)
truth_svgr=breakpointRanges(truth_vcf)
```


# Fun
```{r truth matches}
# delly
delly.bpr$truth_matches=countBreakpointOverlaps(delly.bpr, truth_svgr, maxgap=100, sizemargin=0.25, 
                                                
                                                restrictMarginToSizeMultiple=0.5, 
                                                
                                                countOnlyBest=TRUE)

# svaba
svaba.bpr$truth_matches=countBreakpointOverlaps(svaba.bpr, truth_svgr, maxgap=100, sizemargin=0.25, 
                                                
                                                restrictMarginToSizeMultiple=0.5, 
                                                
                                                countOnlyBest=TRUE)

# manta
manta.bpr$truth_matches=countBreakpointOverlaps(manta.bpr, truth_svgr, maxgap=100, sizemargin=0.25, 
                                                
                                                restrictMarginToSizeMultiple=0.5, 
                                                
                                                countOnlyBest=TRUE)

# Wham
wham.bpr$truth_matches=countBreakpointOverlaps(wham.bpr, truth_svgr, maxgap=100, sizemargin=0.25, 
                                                
                                                restrictMarginToSizeMultiple=0.5, 
                                                
                                                countOnlyBest=TRUE)


# Melt
melt.bpr$truth_matches=countBreakpointOverlaps(melt.bpr, truth_svgr, maxgap=100, sizemargin=0.25, 
                                                
                                                restrictMarginToSizeMultiple=0.5, 
                                                
                                                countOnlyBest=TRUE)
```

```{r Boxplots 1}
boxplot(delly.bpr$support~delly.bpr$truth_matches)
boxplot(manta.bpr$support~manta.bpr$truth_matches)
boxplot(svaba.bpr$support~svaba.bpr$truth_matches)
boxplot(melt.bpr$support~melt.bpr$truth_matches)
boxplot(wham.bpr$support~wham.bpr$truth_matches)
```


```{r Boxplot 2}
table(delly.bpr$truth_matches)
delly.match=delly.bpr[which(delly.bpr$truth_matches>0)]
table(delly.match$truth_matches)
boxplot(delly.match$support)
```

```{r Generalisation of Boxplot 2}
delly.match=delly.bpr[which(delly.bpr$truth_matches>0)]
manta.match=manta.bpr[which(manta.bpr$truth_matches>0)]
svaba.match=svaba.bpr[which(svaba.bpr$truth_matches>0)]
melt.match=melt.bpr[which(melt.bpr$truth_matches>0)]
wham.match=wham.bpr[which(wham.bpr$truth_matches>0)]

# extract $support, $tot_depth and $Callers from each GR
# then concatenate to one data frame for plotting
```






